//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject1
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    using WebTest.WebService.Plugin.Runtime;


    public class ReadVoteCommentTest : WebTest
    {

        private WebServicePlugin testPlugin0 = new WebServicePlugin();

        public ReadVoteCommentTest()
        {
            this.PreAuthenticate = true;
            this.PreWebTest += new EventHandler<PreWebTestEventArgs>(this.testPlugin0.PreWebTest);
            this.PostWebTest += new EventHandler<PostWebTestEventArgs>(this.testPlugin0.PostWebTest);
            this.PreTransaction += new EventHandler<PreTransactionEventArgs>(this.testPlugin0.PreTransaction);
            this.PostTransaction += new EventHandler<PostTransactionEventArgs>(this.testPlugin0.PostTransaction);
            this.PrePage += new EventHandler<PrePageEventArgs>(this.testPlugin0.PrePage);
            this.PostPage += new EventHandler<PostPageEventArgs>(this.testPlugin0.PostPage);
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }
            this.PreRequestDataBinding += new EventHandler<PreRequestDataBindingEventArgs>(this.testPlugin0.PreRequestDataBinding);
            this.PreRequest += new EventHandler<PreRequestEventArgs>(this.testPlugin0.PreRequest);
            this.PostRequest += new EventHandler<PostRequestEventArgs>(this.testPlugin0.PostRequest);

            WebTestRequest request1 = new WebTestRequest("http://beta.blahgua.com/");
            WebTestRequest request1Dependent1 = new WebTestRequest("http://themes.googleusercontent.com/static/fonts/arimo/v4/kJziZB9mN1Zz67hE4Xj10w." +
                    "eot");
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("http://themes.googleusercontent.com/static/fonts/arimo/v4/5Pu1hU3bOP0NyOZx3DCeVve" +
                    "sZW2xOQ-xsNqO47m55DA.eot");
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("http://themes.googleusercontent.com/static/fonts/arimo/v4/thDv13z50gThh9VG9EA2iA." +
                    "eot");
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("http://themes.googleusercontent.com/static/fonts/arimo/v4/_K7sg-ijHdmkwPzV9FiqaFQ" +
                    "lYEbsez9cZjKsNMjLOwM.eot");
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahPreview.html");
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request1.DependentRequests.Add(request1Dependent5);
            WebTestRequest request1Dependent6 = new WebTestRequest("http://beta.blahgua.com/v2/groups/featured");
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent6.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request1Dependent6.QueryStringParameters.Add("", "{}", false, false);
            request1.DependentRequests.Add(request1Dependent6);
            WebTestRequest request1Dependent7 = new WebTestRequest("http://beta.blahgua.com/v2/blahs/types");
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request1Dependent7.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request1Dependent7.QueryStringParameters.Add("", "{}", false, false);
            request1.DependentRequests.Add(request1Dependent7);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request2.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request2.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request2.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request2.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request2.QueryStringParameters.Add("start", "0", false, false);
            request2.QueryStringParameters.Add("count", "100", false, false);
            request2.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request3.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request3.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request3.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request3.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request4.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request4.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request4.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request4.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request4.QueryStringParameters.Add("start", "0", false, false);
            request4.QueryStringParameters.Add("count", "100", false, false);
            request4.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request5.ThinkTime = 2;
            request5.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request5.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request5.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request5.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request5.QueryStringParameters.Add("start", "0", false, false);
            request5.QueryStringParameters.Add("count", "100", false, false);
            request5.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request6.ThinkTime = 1;
            request6.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request6.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request6.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request6.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("http://beta.blahgua.com/v2/blahs/517ab7c4e4b070fd16206682");
            request7.ThinkTime = 1;
            request7.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request7.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request7.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request7.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request7.QueryStringParameters.Add("", "{}", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahDetailPage.html");
            request8.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request8.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request9.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request9.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request9.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request9.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahBodyDetailPage.html");
            request10.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request10.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("http://beta.blahgua.com/v2/blahs/517ab7c4e4b070fd16206682");
            request11.Method = "PUT";
            request11.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request11.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request11.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request11.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            StringHttpBody request11Body = new StringHttpBody();
            request11Body.ContentType = "application/json; charset=utf-8";
            request11Body.InsertByteOrderMark = false;
            request11Body.BodyString = "{\"V\":0, \"O\":1}";
            request11.Body = request11Body;
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("http://beta.blahgua.com/v2/users/descriptor");
            request12.ThinkTime = 1;
            request12.Method = "POST";
            request12.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request12.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request12.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            StringHttpBody request12Body = new StringHttpBody();
            request12Body.ContentType = "application/json; charset=utf-8";
            request12Body.InsertByteOrderMark = false;
            request12Body.BodyString = "{\"I\":\"517ab7b3e4b070fd1620647e\"}";
            request12.Body = request12Body;
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request13.ThinkTime = 2;
            request13.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request13.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request13.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request13.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/SignUpPage.html");
            request14.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request14.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request15.ThinkTime = 2;
            request15.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request15.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request15.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request15.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request16.ThinkTime = 2;
            request16.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request16.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request16.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request16.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request17.ThinkTime = 2;
            request17.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request17.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request17.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request17.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request18.ThinkTime = 2;
            request18.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request18.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request18.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request18.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request19.ThinkTime = 2;
            request19.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request19.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request19.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request19.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request20.ThinkTime = 2;
            request20.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request20.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request20.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request20.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("http://beta.blahgua.com/v2/users/login");
            request21.Method = "POST";
            request21.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request21.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request21.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            StringHttpBody request21Body = new StringHttpBody();
            request21Body.ContentType = "application/json; charset=utf-8";
            request21Body.InsertByteOrderMark = false;
            request21Body.BodyString = "{\"N\":\"davevr\", \"pwd\":\"Love4Ru\"}";
            request21.Body = request21Body;
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("http://beta.blahgua.com/v2/users/profile/schema");
            request22.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request22.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request22.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request22.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("http://beta.blahgua.com/v2/users/info");
            request23.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request23.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request23.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request23.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request23.QueryStringParameters.Add("", "{}", false, false);
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("http://beta.blahgua.com/v2/userGroups");
            request24.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request24.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request24.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request24.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request24.QueryStringParameters.Add("", "{}", false, false);
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request25.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request25.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request25.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request25.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request25.QueryStringParameters.Add("start", "0", false, false);
            request25.QueryStringParameters.Add("count", "100", false, false);
            request25.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request26.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request26.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request26.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request26.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request27.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request27.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request27.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request27.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request27.QueryStringParameters.Add("start", "0", false, false);
            request27.QueryStringParameters.Add("count", "100", false, false);
            request27.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request28.ThinkTime = 2;
            request28.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request28.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request28.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request28.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request28.QueryStringParameters.Add("start", "0", false, false);
            request28.QueryStringParameters.Add("count", "100", false, false);
            request28.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request29.ThinkTime = 1;
            request29.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request29.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request29.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request29.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahDetailPage.html");
            request30.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request30.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahBodyDetailPage.html");
            request31.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request31.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request32.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request32.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request32.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request32.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("http://beta.blahgua.com/v2/blahs/517ab7c4e4b070fd16206682");
            request33.Method = "PUT";
            request33.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request33.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request33.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request33.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            StringHttpBody request33Body = new StringHttpBody();
            request33Body.ContentType = "application/json; charset=utf-8";
            request33Body.InsertByteOrderMark = false;
            request33Body.BodyString = "{\"V\":0, \"O\":1}";
            request33.Body = request33Body;
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("http://beta.blahgua.com/v2/users/descriptor");
            request34.ThinkTime = 2;
            request34.Method = "POST";
            request34.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request34.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request34.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            StringHttpBody request34Body = new StringHttpBody();
            request34Body.ContentType = "application/json; charset=utf-8";
            request34Body.InsertByteOrderMark = false;
            request34Body.BodyString = "{\"I\":\"517ab7b3e4b070fd1620647e\"}";
            request34.Body = request34Body;
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request35.ThinkTime = 2;
            request35.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request35.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request35.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request35.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request36.ThinkTime = 2;
            request36.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request36.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request36.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request36.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahCommentDetailPage.html");
            request37.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request37.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request38.ThinkTime = 2;
            request38.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request38.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request38.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request38.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request39.ThinkTime = 2;
            request39.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request39.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request39.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request39.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request39;
            request39 = null;

            WebTestRequest request40 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request40.ThinkTime = 1;
            request40.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request40.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request40.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request40.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request40;
            request40 = null;

            WebTestRequest request41 = new WebTestRequest("http://beta.blahgua.com/v2/comments");
            request41.Method = "POST";
            request41.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request41.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request41.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            StringHttpBody request41Body = new StringHttpBody();
            request41Body.ContentType = "application/json; charset=utf-8";
            request41Body.InsertByteOrderMark = false;
            request41Body.BodyString = "{\"T\":\"This is a comment\", \"B\":\"517ab7c4e4b070fd16206682\"}";
            request41.Body = request41Body;
            yield return request41;
            request41 = null;

            WebTestRequest request42 = new WebTestRequest("http://beta.blahgua.com/v2/comments");
            request42.ThinkTime = 1;
            request42.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request42.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request42.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request42.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request42.QueryStringParameters.Add("blahId", "517ab7c4e4b070fd16206682", false, false);
            yield return request42;
            request42 = null;

            WebTestRequest request43 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request43.ThinkTime = 2;
            request43.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request43.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request43.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request43.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request43;
            request43 = null;

            WebTestRequest request44 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request44.ThinkTime = 2;
            request44.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request44.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request44.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request44.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request44;
            request44 = null;

            WebTestRequest request45 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request45.ThinkTime = 1;
            request45.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request45.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request45.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request45.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request45;
            request45 = null;

            WebTestRequest request46 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahStatsDetailPage.html");
            request46.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request46.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request46;
            request46 = null;

            WebTestRequest request47 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahAuthorPage.html");
            request47.ThinkTime = 1;
            request47.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request47.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request47;
            request47 = null;

            WebTestRequest request48 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request48.ThinkTime = 2;
            request48.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request48.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request48.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request48.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request48;
            request48 = null;

            WebTestRequest request49 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request49.ThinkTime = 1;
            request49.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request49.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request49.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request49.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request49;
            request49 = null;

            WebTestRequest request50 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahStatsDetailPage.html");
            request50.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request50.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request50;
            request50 = null;

            WebTestRequest request51 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahCommentDetailPage.html");
            request51.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request51.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request51;
            request51 = null;

            WebTestRequest request52 = new WebTestRequest("http://beta.blahgua.com/v2/comments");
            request52.ThinkTime = 1;
            request52.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request52.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request52.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request52.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request52.QueryStringParameters.Add("blahId", "517ab7c4e4b070fd16206682", false, false);
            yield return request52;
            request52 = null;

            WebTestRequest request53 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request53.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request53.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request53.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request53.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request53;
            request53 = null;

            WebTestRequest request54 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahStatsDetailPage.html");
            request54.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request54.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request54;
            request54 = null;

            WebTestRequest request55 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahAuthorPage.html");
            request55.ThinkTime = 2;
            request55.Headers.Add(new WebTestRequestHeader("Accept", "text/html, */*; q=0.01"));
            request55.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request55;
            request55 = null;

            WebTestRequest request56 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request56.ThinkTime = 1;
            request56.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request56.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request56.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request56.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request56;
            request56 = null;

            WebTestRequest request57 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request57.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request57.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request57.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request57.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request57.QueryStringParameters.Add("start", "0", false, false);
            request57.QueryStringParameters.Add("count", "100", false, false);
            request57.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request57;
            request57 = null;

            WebTestRequest request58 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request58.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request58.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request58.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request58.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request58.QueryStringParameters.Add("start", "0", false, false);
            request58.QueryStringParameters.Add("count", "100", false, false);
            request58.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request58;
            request58 = null;

            WebTestRequest request59 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request59.ThinkTime = 1;
            request59.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request59.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request59.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request59.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            request59.QueryStringParameters.Add("start", "0", false, false);
            request59.QueryStringParameters.Add("count", "100", false, false);
            request59.QueryStringParameters.Add("groupId", "517a2f2ae4b089a0931584d0", false, false);
            yield return request59;
            request59 = null;

            WebTestRequest request60 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517a2f2ae4b089a0931584d0/viewerCount");
            request60.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request60.Headers.Add(new WebTestRequestHeader("Accept", "application/json, text/javascript, */*; q=0.01"));
            request60.Headers.Add(new WebTestRequestHeader("X-Requested-With", "XMLHttpRequest"));
            request60.Headers.Add(new WebTestRequestHeader("Referer", "http://beta.blahgua.com/"));
            yield return request60;
            request60 = null;
        }
    }
}
