//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject1 {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    
    
    public class WebTest1Coded : WebTest {
        
        public WebTest1Coded() {
            this.PreAuthenticate = true;
        }
        
        public override IEnumerator<WebTestRequest> GetRequestEnumerator() {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("http://beta.blahgua.com/");
            WebTestRequest request1Dependent1 = new WebTestRequest("http://themes.googleusercontent.com/static/fonts/arimo/v4/kJziZB9mN1Zz67hE4Xj10w." +
                    "eot");
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("http://themes.googleusercontent.com/static/fonts/arimo/v4/5Pu1hU3bOP0NyOZx3DCeVve" +
                    "sZW2xOQ-xsNqO47m55DA.eot");
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("http://themes.googleusercontent.com/static/fonts/arimo/v4/thDv13z50gThh9VG9EA2iA." +
                    "eot");
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("http://themes.googleusercontent.com/static/fonts/arimo/v4/_K7sg-ijHdmkwPzV9FiqaFQ" +
                    "lYEbsez9cZjKsNMjLOwM.eot");
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("http://beta.blahgua.com/v2/users/login");
            request1Dependent5.Method = "POST";
            StringHttpBody request1Dependent5Body = new StringHttpBody();
            request1Dependent5Body.ContentType = "application/json; charset=utf-8";
            request1Dependent5Body.InsertByteOrderMark = false;
            request1Dependent5Body.BodyString = "{\"N\":\"test_0010\", \"pwd\":\"Secret\"}";
            request1Dependent5.Body = request1Dependent5Body;
            request1.DependentRequests.Add(request1Dependent5);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("http://beta.blahgua.com/v2/users/profile/schema");
            request2.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("http://beta.blahgua.com/v2/users/info");
            request3.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request3.QueryStringParameters.Add("", "{}", false, false);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/BlahPreview.html");
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("http://beta.blahgua.com/v2/userGroups");
            request5.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request5.QueryStringParameters.Add("", "{}", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("http://beta.blahgua.com/v2/blahs/types");
            request6.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request6.QueryStringParameters.Add("", "{}", false, false);
            yield return request6;
            request6 = null;

            ContextParameterExistenceRule conditionalRule1 = new ContextParameterExistenceRule();
            conditionalRule1.ContextParameterName = "LoggedIn";
            conditionalRule1.CheckForExistence = true;

            int maxIterations1 = 3;
            bool advanceDataCursors1 = false;
            this.BeginLoop(conditionalRule1, maxIterations1, advanceDataCursors1);

            for (; this.ExecuteConditionalRule(conditionalRule1); ) {
                WebTestRequest request7 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
                request7.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
                request7.QueryStringParameters.Add("start", "0", false, false);
                request7.QueryStringParameters.Add("count", "100", false, false);
                request7.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9b9", false, false);
                yield return request7;
                request7 = null;
            }

            this.EndLoop(conditionalRule1);

            WebTestRequest request8 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9b9/viewerCount");
            request8.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request9.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request9.QueryStringParameters.Add("start", "0", false, false);
            request9.QueryStringParameters.Add("count", "100", false, false);
            request9.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9b9", false, false);
            yield return request9;
            request9 = null;

            LastResponseCodeRule conditionalRule2 = new LastResponseCodeRule();
            conditionalRule2.ComparisonOperator = StringComparisonOperator.Equality;
            conditionalRule2.ResponseCode = WebTestResponseCode.Ok;

            this.BeginCondition(conditionalRule2);

            if (this.ExecuteConditionalRule(conditionalRule2)) {
                WebTestRequest request10 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
                request10.ThinkTime = 2;
                request10.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
                request10.QueryStringParameters.Add("start", "0", false, false);
                request10.QueryStringParameters.Add("count", "100", false, false);
                request10.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9b9", false, false);
                yield return request10;
                request10 = null;

                WebTestRequest request11 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9b9/viewerCount");
                request11.ThinkTime = 2;
                request11.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
                yield return request11;
                request11 = null;
            }

            this.EndCondition(conditionalRule2);

            WebTestRequest request12 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9b9/viewerCount");
            request12.ThinkTime = 1;
            request12.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request13.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request13.QueryStringParameters.Add("start", "0", false, false);
            request13.QueryStringParameters.Add("count", "100", false, false);
            request13.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9b9", false, false);
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9b9/viewerCount");
            request14.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request15.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request15.QueryStringParameters.Add("start", "0", false, false);
            request15.QueryStringParameters.Add("count", "100", false, false);
            request15.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9b9", false, false);
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request16.ThinkTime = 2;
            request16.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request16.QueryStringParameters.Add("start", "0", false, false);
            request16.QueryStringParameters.Add("count", "100", false, false);
            request16.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9b9", false, false);
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9b9/viewerCount");
            request17.ThinkTime = 2;
            request17.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9b9/viewerCount");
            request18.ThinkTime = 2;
            request18.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9b9/viewerCount");
            request19.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request20.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request20.QueryStringParameters.Add("start", "0", false, false);
            request20.QueryStringParameters.Add("count", "100", false, false);
            request20.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request21.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request22.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request22.QueryStringParameters.Add("start", "0", false, false);
            request22.QueryStringParameters.Add("count", "100", false, false);
            request22.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request23.ThinkTime = 2;
            request23.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request23.QueryStringParameters.Add("start", "0", false, false);
            request23.QueryStringParameters.Add("count", "100", false, false);
            request23.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request24.ThinkTime = 1;
            request24.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/CreateBlahPage.html");
            request25.ThinkTime = 1;
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request26.ThinkTime = 2;
            request26.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request27.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request28.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request28.QueryStringParameters.Add("start", "0", false, false);
            request28.QueryStringParameters.Add("count", "100", false, false);
            request28.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request29.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request29.QueryStringParameters.Add("start", "0", false, false);
            request29.QueryStringParameters.Add("count", "100", false, false);
            request29.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request30.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request30.QueryStringParameters.Add("start", "0", false, false);
            request30.QueryStringParameters.Add("count", "100", false, false);
            request30.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request31.ThinkTime = 1;
            request31.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request31.QueryStringParameters.Add("start", "0", false, false);
            request31.QueryStringParameters.Add("count", "100", false, false);
            request31.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request32.ThinkTime = 1;
            request32.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/ChannelBrowser.html");
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("http://beta.blahgua.com/v2/groupTypes");
            request34.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request34.QueryStringParameters.Add("", "{}", false, false);
            yield return request34;
            request34 = null;

            WebTestRequest request35 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request35.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request35.QueryStringParameters.Add("start", "0", false, false);
            request35.QueryStringParameters.Add("count", "100", false, false);
            request35.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request35;
            request35 = null;

            WebTestRequest request36 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request36.ThinkTime = 1;
            request36.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request36;
            request36 = null;

            WebTestRequest request37 = new WebTestRequest("http://beta.blahgua.com/v2/groups");
            request37.ThinkTime = 1;
            request37.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request37.QueryStringParameters.Add("type", "517879aee4b0a476433fa9b2", false, false);
            request37.QueryStringParameters.Add("", "{}", false, false);
            yield return request37;
            request37 = null;

            WebTestRequest request38 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request38.ThinkTime = 1;
            request38.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request38;
            request38 = null;

            WebTestRequest request39 = new WebTestRequest("http://beta.blahgua.com/v2/groups");
            request39.ThinkTime = 1;
            request39.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request39.QueryStringParameters.Add("type", "517879aee4b0a476433fa9b6", false, false);
            request39.QueryStringParameters.Add("", "{}", false, false);
            yield return request39;
            request39 = null;

            WebTestRequest request40 = new WebTestRequest("http://beta.blahgua.com/v2/groups");
            request40.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request40.QueryStringParameters.Add("type", "517879aee4b0a476433fa9b4", false, false);
            request40.QueryStringParameters.Add("", "{}", false, false);
            yield return request40;
            request40 = null;

            WebTestRequest request41 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request41.ThinkTime = 1;
            request41.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request41;
            request41 = null;

            WebTestRequest request42 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/ChannelDetailPage.html");
            yield return request42;
            request42 = null;

            WebTestRequest request43 = new WebTestRequest("http://beta.blahgua.com/v2/groups");
            request43.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request43.QueryStringParameters.Add("type", "", false, false);
            request43.QueryStringParameters.Add("", "{}", false, false);
            yield return request43;
            request43 = null;

            WebTestRequest request44 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba");
            request44.ThinkTime = 1;
            request44.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request44.QueryStringParameters.Add("", "{}", false, false);
            yield return request44;
            request44 = null;

            WebTestRequest request45 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request45.ThinkTime = 1;
            request45.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request45;
            request45 = null;

            WebTestRequest request46 = new WebTestRequest("http://beta.blahgua.com/v2/userGroups");
            request46.ThinkTime = 1;
            request46.Method = "DELETE";
            request46.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            StringHttpBody request46Body = new StringHttpBody();
            request46Body.ContentType = "application/json; charset=utf-8";
            request46Body.InsertByteOrderMark = false;
            request46Body.BodyString = "{\'g\':\'517879aee4b0a476433fa9ba\'}";
            request46.Body = request46Body;
            yield return request46;
            request46 = null;

            WebTestRequest request47 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request47.ThinkTime = 2;
            request47.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request47;
            request47 = null;

            WebTestRequest request48 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request48.ThinkTime = 2;
            request48.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request48;
            request48 = null;

            WebTestRequest request49 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request49.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request49;
            request49 = null;

            WebTestRequest request50 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/ChannelBrowser.html");
            yield return request50;
            request50 = null;

            WebTestRequest request51 = new WebTestRequest("http://beta.blahgua.com/v2/groupTypes");
            request51.ThinkTime = 1;
            request51.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request51.QueryStringParameters.Add("", "{}", false, false);
            yield return request51;
            request51 = null;

            this.BeginTransaction("DoThisAtOnce");

            WebTestRequest request52 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request52.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request52.QueryStringParameters.Add("start", "0", false, false);
            request52.QueryStringParameters.Add("count", "100", false, false);
            request52.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request52;
            request52 = null;

            this.EndTransaction("DoThisAtOnce");

            WebTestRequest request53 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request53.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request53.QueryStringParameters.Add("start", "0", false, false);
            request53.QueryStringParameters.Add("count", "100", false, false);
            request53.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request53;
            request53 = null;

            WebTestRequest request54 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request54.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request54.Headers.Add(new WebTestRequestHeader("", ""));
            request54.QueryStringParameters.Add("start", "0", false, false);
            request54.QueryStringParameters.Add("count", "100", false, false);
            request54.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request54;
            request54 = null;

            WebTestRequest request55 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request55.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request55.QueryStringParameters.Add("start", "0", false, false);
            request55.QueryStringParameters.Add("count", "100", false, false);
            request55.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request55;
            request55 = null;

            WebTestRequest request56 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request56.ThinkTime = 2;
            request56.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request56;
            request56 = null;

            WebTestRequest request57 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request57.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request57.QueryStringParameters.Add("start", "0", false, false);
            request57.QueryStringParameters.Add("count", "100", false, false);
            request57.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9bc", false, false);
            yield return request57;
            request57 = null;

            WebTestRequest request58 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9bc/viewerCount");
            request58.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request58;
            request58 = null;

            WebTestRequest request59 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request59.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request59.QueryStringParameters.Add("start", "0", false, false);
            request59.QueryStringParameters.Add("count", "100", false, false);
            request59.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9bc", false, false);
            yield return request59;
            request59 = null;

            WebTestRequest request60 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request60.ThinkTime = 1;
            request60.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request60.QueryStringParameters.Add("start", "0", false, false);
            request60.QueryStringParameters.Add("count", "100", false, false);
            request60.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9bc", false, false);
            yield return request60;
            request60 = null;

            WebTestRequest request61 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request61.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request61.QueryStringParameters.Add("start", "0", false, false);
            request61.QueryStringParameters.Add("count", "100", false, false);
            request61.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request61;
            request61 = null;

            WebTestRequest request62 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request62.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request62;
            request62 = null;

            WebTestRequest request63 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request63.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request63.QueryStringParameters.Add("start", "0", false, false);
            request63.QueryStringParameters.Add("count", "100", false, false);
            request63.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request63;
            request63 = null;

            WebTestRequest request64 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request64.ThinkTime = 2;
            request64.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request64.QueryStringParameters.Add("start", "0", false, false);
            request64.QueryStringParameters.Add("count", "100", false, false);
            request64.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request64;
            request64 = null;

            WebTestRequest request65 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request65.ThinkTime = 1;
            request65.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request65;
            request65 = null;

            WebTestRequest request66 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/ChannelBrowser.html");
            yield return request66;
            request66 = null;

            WebTestRequest request67 = new WebTestRequest("http://beta.blahgua.com/v2/groupTypes");
            request67.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request67.QueryStringParameters.Add("", "{}", false, false);
            yield return request67;
            request67 = null;

            WebTestRequest request68 = new WebTestRequest("http://beta.blahgua.com/v2/users/inbox");
            request68.ThinkTime = 1;
            request68.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request68.QueryStringParameters.Add("start", "0", false, false);
            request68.QueryStringParameters.Add("count", "100", false, false);
            request68.QueryStringParameters.Add("groupId", "517879aee4b0a476433fa9ba", false, false);
            yield return request68;
            request68 = null;

            WebTestRequest request69 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request69.ThinkTime = 1;
            request69.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request69;
            request69 = null;

            WebTestRequest request70 = new WebTestRequest("http://beta.blahgua.com/v2/groups");
            request70.ThinkTime = 1;
            request70.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request70.QueryStringParameters.Add("type", "517879aee4b0a476433fa9b4", false, false);
            request70.QueryStringParameters.Add("", "{}", false, false);
            yield return request70;
            request70 = null;

            WebTestRequest request71 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request71.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request71;
            request71 = null;

            WebTestRequest request72 = new WebTestRequest("http://blahgua-webapp.s3.amazonaws.com/pages/ChannelDetailPage.html");
            yield return request72;
            request72 = null;

            WebTestRequest request73 = new WebTestRequest("http://beta.blahgua.com/v2/groups");
            request73.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request73.QueryStringParameters.Add("type", "", false, false);
            request73.QueryStringParameters.Add("", "{}", false, false);
            yield return request73;
            request73 = null;

            WebTestRequest request74 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba");
            request74.ThinkTime = 2;
            request74.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            request74.QueryStringParameters.Add("", "{}", false, false);
            yield return request74;
            request74 = null;

            WebTestRequest request75 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request75.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request75;
            request75 = null;

            WebTestRequest request76 = new WebTestRequest("http://beta.blahgua.com/v2/userGroups");
            request76.ThinkTime = 1;
            request76.Method = "DELETE";
            request76.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            StringHttpBody request76Body = new StringHttpBody();
            request76Body.ContentType = "application/json; charset=utf-8";
            request76Body.InsertByteOrderMark = false;
            request76Body.BodyString = "{\'g\':\'517879aee4b0a476433fa9ba\'}";
            request76.Body = request76Body;
            yield return request76;
            request76 = null;

            WebTestRequest request77 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request77.ThinkTime = 2;
            request77.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request77;
            request77 = null;

            WebTestRequest request78 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request78.ThinkTime = 2;
            request78.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request78;
            request78 = null;

            WebTestRequest request79 = new WebTestRequest("http://beta.blahgua.com/v2/groups/517879aee4b0a476433fa9ba/viewerCount");
            request79.Headers.Add(new WebTestRequestHeader("Content-Type", "application/json; charset=utf-8"));
            yield return request79;
            request79 = null;
        }
    }
}
